# Generated by Django 5.1.1 on 2024-09-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rarity",
            field=models.CharField(
                choices=[("Common", "Common"), ("Rare", "Rare"), ("Secret", "Secret")],
                default="Common",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
